name: 'Vowel Frequency Analyzer'
description: 'Custom action to analyse vowels frequency'

inputs:
  file:
    description: 'The path to the text file to analyze (e.g., data.txt).'
    required: true

runs:
  using: docker
  image: Dockerfile
  entrypoint: ['/bin/bash', '/github/scripts/entrypoint.sh']
  env:
    FILE: ${{ inputs.file }}